/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prestoq.code;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;

public class App {
    public static void main(String[] args) {
	try {
	    BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(args[0])));

	    String line;
	    while ((line = br.readLine()) != null) {
		ProductRecord record = new ProductRecord.Builder(line).build();
		System.out.println(record.toString());
	    }
	    br.close();

	} catch (java.io.IOException e) {
	    e.printStackTrace();
	}
    }
}
